import{a as u,S as y,i as c}from"./assets/vendor-89feecc5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const r={input:document.querySelector('[type="text"]'),searchBtn:document.querySelector('[type="submit"]'),gallery:document.querySelector(".gallery"),loadBtn:document.querySelector(".js-load"),loadDiv:document.querySelector(".js-loader")},m={API_KEY:"41488002-513c6a9a4c115eae6a99045d3"};u.defaults.baseURL="https://pixabay.com/api/";let s=1;const d=40;let p=new y(".gallery a");async function f(n=s){try{return(await u.get(`?key=${m.API_KEY}&q=${r.input.value}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=${d}`)).data}catch(e){console.error(e)}}r.searchBtn.addEventListener("click",L);r.loadBtn.addEventListener("click",v);async function L(n){if(n.preventDefault(),s=1,r.input.value.trim()==="")return c.error({message:"Sorry, the field must be filled in!",position:"topRight"});r.gallery.innerHTML='<span class="loader"></span>';try{const e=await f();r.gallery.innerHTML=h(e.hits),p.refresh(),e.hits.length>0&&c.info({message:`Total Hits: ${e.totalHits}, Loaded Files: ${e.hits.length}`,position:"topRight"}),r.loadBtn.hidden=d>=e.totalHits}catch(e){console.error(e)}}async function v(n){n.preventDefault(),s+=1,r.loadDiv.innerHTML='<span class="loader"></span>',r.loadBtn.hidden=!0;try{const e=await f(s);r.gallery.insertAdjacentHTML("beforeend",h(e.hits)),p.refresh(),c.info({message:`Loaded Files: ${e.hits.length}`,position:"topRight"}),e.totalHits/d<=s?(r.loadBtn.hidden=!0,r.loadDiv.innerHTML="",c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):e.totalHits/d>=s&&(r.loadDiv.innerHTML="",r.loadBtn.hidden=!1);let a=document.querySelector(".gallery-item").getBoundingClientRect();scrollBy({top:a.height*3,behavior:"smooth"})}catch(e){console.error(e)}}function h(n){return n.length===0&&c.error({message:"Sorry, there are no images matching <br> your search query. Please try again!",position:"topRight"}),n.map(({webformatURL:e,largeImageURL:i,tags:a,likes:t,views:o,comments:l,downloads:g})=>`
    <li class='gallery-item'>
        <a href='${i}'>
            <img src="${e}" alt="${a}" data-source=${i} class='gallery-img'/>
        </a>
        <div class='text-container'>
            <p>Likes<span>${t}</span></p>
            <p>Views<span>${o}</span></p>
            <p>Comments<span>${l}</span></p>
            <p>Downloads<span>${g}</span></p>
        </div>
    </li>`).join("")}
//# sourceMappingURL=commonHelpers.js.map
