import{a as h,s as C,i as d}from"./assets/vendor-2b14a7bb.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const E=document.querySelector(".search-form"),u=document.querySelector(".search-input"),m=document.querySelector(".gallery"),n=document.querySelector(".loader");n.style.display="none";let l=1;const y=40,p=document.querySelector(".load-more");p.style.display="none";let c="";h.defaults.baseURL="https://pixabay.com";const g="/api/";let f=new C("ul.gallery a",{captionDelay:250,captionsData:"alt"});E.addEventListener("submit",async o=>{if(o.preventDefault(),c=u.value.trim(),m.innerHTML="",u.value="",c!==""){n.style.display="block",u.value="",l=1;try{const t=await h.get(g,{params:L(c)});n.style.display="none";const s=t.data;if(s.hits.length===0)throw d.show({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",backgroundColor:"#EF4040",titleColor:"white",position:"topRight"});w(s.hits),s.totalHits<=y*l?(b(),d.show({message:"You've reached the end of search results.",theme:"dark",backgroundColor:"#EF4040",titleColor:"white",position:"topRight"})):R(),f.refresh()}catch(t){v(t)}}});p.addEventListener("click",async()=>{l+=1;try{const o=await h.get(g,{params:L(c)});n.style.display="none";const t=o.data;t.totalHits<=y*l&&(b(),d.show({message:"You've reached the end of search results.",theme:"dark",backgroundColor:"#EF4040",titleColor:"white",position:"topRight"})),w(t.hits),$(),f.refresh()}catch(o){v(o)}});const w=o=>{const t=o.reduce((s,{webformatURL:i,largeImageURL:e,tags:r,likes:a,views:k,comments:q,downloads:S})=>s+`<li class="gallery-item">
          <a class="gallery-link" href="${e}">
           <img class="gallery-image"
           src="${i}"
           alt="${r}"
           />
          </a>          
          <div class="description">
          <p>Likes:<span>${a}</span></p>
          <p>Views:<span>${k}</span></p>
          <p>Comments:<span>${q}</span></p>
          <p>Downloads:<span>${S}</span></p>
          </div> 
        </li>`,"");m.insertAdjacentHTML("beforeend",t)},b=()=>{p.style.display="none"},R=()=>{p.style.display="block"},$=()=>{const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})},L=o=>new URLSearchParams({key:"41544078-5d11fd93221b0dd23a16f477d",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:l,per_page:y}),v=o=>{n.style.display="none",d.error({message:o.message||"Error fetching data",color:"red",position:"topRight"})};
//# sourceMappingURL=commonHelpers.js.map
