import{a as g,S as L,i as a}from"./assets/vendor-89feecc5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const o={input:document.querySelector('[type="text"]'),searchBtn:document.querySelector('[type="submit"]'),gallery:document.querySelector(".gallery"),loadBtn:document.querySelector(".js-load"),loadDiv:document.querySelector(".js-loader")},v={API_KEY:"41488002-513c6a9a4c115eae6a99045d3"};g.defaults.baseURL="https://pixabay.com/api/";let s=1;const d=40;let f=new L(".gallery a"),p;function u(n){o.loadDiv.innerHTML=n?'<span class="loader"></span>':"",o.loadBtn.classList.toggle("hidden",!n)}async function h(n=s){try{return(await g.get(`?key=${v.API_KEY}&q=${o.input.value}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=${d}`)).data}catch(e){console.error(e),a.error({message:"Oops! Something went wrong. Please try again later.",position:"topRight"})}}o.searchBtn.addEventListener("click",$);o.loadBtn.addEventListener("click",S);async function $(n){if(n.preventDefault(),o.input.value.trim()===""){a.error({message:"Sorry, the field must be filled in!",position:"topRight"});return}s=1,u(!0);try{const e=await h();o.gallery.innerHTML=y(e.hits),f.refresh(),e.hits.length>0&&a.info({message:`Total Hits: ${e.totalHits}, Loaded Files: ${e.hits.length}`,position:"topRight"}),o.loadBtn.classList.toggle("hidden",d>=e.totalHits)}catch(e){console.error(e)}finally{u(!1)}}async function S(n){n.preventDefault(),s+=1,u(!0);try{const e=await h(s);o.gallery.insertAdjacentHTML("beforeend",y(e.hits)),f.refresh(),a.info({message:`Loaded Files: ${e.hits.length}`,position:"topRight"}),e.totalHits/d<=s?(o.loadBtn.classList.toggle("hidden",!0),o.loadDiv.innerHTML="",a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):e.totalHits/d>=s&&(o.loadDiv.innerHTML="",o.loadBtn.classList.toggle("hidden",!1)),p=document.querySelector(".gallery-item").getBoundingClientRect().height,scrollBy({top:p*3,behavior:"smooth"})}catch(e){console.error(e)}finally{u(!1)}}function y(n){return n.length===0&&a.error({message:"Sorry, there are no images matching <br> your search query. Please try again!",position:"topRight"}),n.map(({webformatURL:e,largeImageURL:i,tags:c,likes:t,views:r,comments:l,downloads:m})=>`
    <li class='gallery-item'>
        <a href='${i}'>
            <img src="${e}" alt="${c}" data-source=${i} class='gallery-img'/>
        </a>
        <div class='text-container'>
            <p>Likes<span>${t}</span></p>
            <p>Views<span>${r}</span></p>
            <p>Comments<span>${l}</span></p>
            <p>Downloads<span>${m}</span></p>
        </div>
    </li>`).join("")}
//# sourceMappingURL=commonHelpers.js.map
